import type { Metadata } from 'next'
import { Outfit, Young_Serif } from 'next/font/google'
import './globals.css'

const outfit = Outfit({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-outfit',
})
const young = Young_Serif({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-young-serif',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} ${young.variable}`}>{children}</body>
    </html>
  )
}
